### ISSUE TITLE
Discord.js v14

### ISSUE THREAD

**Issue by lennoncoder** [MatrixByte/plexus-djs#1]
Plexus-djs gives support for discord.js 13, while plexus-djs14 gives support for 14. But Plexus-djs14 doesn't have docs, source code, and sometimes doesn't even work properly. pls fix these...

**Comment by avalynndev** [comment]
I understand, pls wait while we fix this issue..

**Comment by avalynndev** [comment]
Fixed

**Comment by avalynndev** [comment]
use `npm install plexus-djs`
